// <auto-generated />
using System;
using MADWORDS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MADWORDS.Migrations
{
    [DbContext(typeof(UpdateContext))]
    [Migration("20201205195919_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MADWORDS.Models.Update", b =>
                {
                    b.Property<int>("UpdateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdateText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UpdateID");

                    b.ToTable("Updates");
                });
#pragma warning restore 612, 618
        }
    }
}
