// <auto-generated />
using System;
using MADWORDS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MADWORDS.Migrations
{
    [DbContext(typeof(MadwordContext))]
    [Migration("20201205092156_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MADWORDS.Models.Madword", b =>
                {
                    b.Property<int>("MadwordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AuthorUserID")
                        .HasColumnType("int");

                    b.Property<DateTime>("MadwordDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MadwordRating")
                        .HasColumnType("int");

                    b.Property<string>("MadwordText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MadwordTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MadwordTopic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MadwordID");

                    b.HasIndex("AuthorUserID");

                    b.ToTable("Madwords");
                });

            modelBuilder.Entity("MADWORDS.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MADWORDS.Models.Madword", b =>
                {
                    b.HasOne("MADWORDS.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorUserID");
                });
#pragma warning restore 612, 618
        }
    }
}
